about/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.about, name='about'),    
		]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('post/<int:pk>/', views.blog_detail, name='blog_detail'),
]

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contact, name='contact'),
]

ganapati/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('service/', include('service.urls')),
    path('testimonial/', include('testimonial.urls')),
   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', views.home, name='home'),
    path('termsCondition', views.termsCondition, name='terms'),
    path('privacyPolicy', views.privacyPolicy, name='privacy'),
    path('subscription', views.subscription, name='subscription'),
   
   
   ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

service/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.service, name='service'),
    
    ]

testimonial/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.testimonial, name='testimonial'),
		]

about/models.py
from django.db import models

class Member(models.Model):
    name = models.CharField(max_length=100)
    role = models.CharField(max_length=100)
    website_link = models.URLField(blank=True)
    facebook_link = models.URLField(blank=True)
    instagram_link = models.URLField(blank=True)
    twitter_link = models.URLField(blank=True)
    linkedin_link = models.URLField(blank=True)
    image = models.ImageField(upload_to='member_images/', blank=True, null=True)

    def __str__(self):
        return self.name

blog/models.py
from django.db import models

class BlogPost(models.Model):
    name = models.CharField(max_length=100)
    issueID = models.CharField(max_length=50)
    thumbnail = models.ImageField(upload_to='blog/thumbnails/')
    video = models.URLField(blank=True)
    image1 = models.ImageField(upload_to='blog/images2/', blank=True)
    image2 = models.ImageField(upload_to='blog/images2/', blank=True)
    image3 = models.ImageField(upload_to='blog/images2/', blank=True)
    image4 = models.ImageField(upload_to='blog/images2/', blank=True)
    image5 = models.ImageField(upload_to='blog/images2/', blank=True)
    category = models.CharField(max_length=50 , default="mobile")
    client = models.CharField(max_length=100 , default="user" , blank=True)
    project_issue = models.DateField()
    project_finish = models.DateField()
    repairing_cost = models.DecimalField(max_digits=10, decimal_places=2 , default="hidden")
    description = models.TextField()

    def __str__(self):
        return self.name

contact/models.py
from django.db import models

class Contact(models.Model):
    fullname = models.CharField(max_length=100)
    email = models.EmailField()
    phonenumber = models.CharField(max_length=15)
    subject = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.fullname

home/models.py
from django.db import models
from django.urls import path, include

class Subscription(models.Model):
	sno = models.AutoField(primary_key=True)
	subscriptionemail = models.EmailField(max_length=50)
	timeStamp = models.DateTimeField(auto_now_add=True, blank=True)

	def __str__(self):
    		return self.subscriptionemail

portfolio/models.py
from django.db import models

service/models.py
from django.db import models

testimonial/models.py
from django.db import models

def get_default_image():
    return '../static/avatar.jpg'

class Post(models.Model):
    name = models.CharField(max_length=100)
    role = models.CharField(max_length=100)
    link = models.CharField(max_length=100)
    image = models.ImageField(upload_to='testimonial_images/', default=get_default_image, blank=True, null=True)
    comment = models.CharField(max_length=500)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['fullname', 'email', 'phonenumber', 'subject', 'description']

about/views.py
from django.shortcuts import render
from .models import Member

def about(request):
    members = Member.objects.all()
    return render(request, 'pages/about.html', {'members': members})

blog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import BlogPost

def blog_list(request):
    posts = BlogPost.objects.all()

    # Number of posts per page
    posts_per_page = 15

    paginator = Paginator(posts, posts_per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj}
    return render(request, 'pages/blog.html', context)

def blog_detail(request, pk):
    post = get_object_or_404(BlogPost, pk=pk)
    context = {'post': post}
    return render(request, 'pages/blog-details.html', context)

contact/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/') 
    else:
        form = ContactForm()
    return render(request, 'pages/contact.html', {'form': form})

home/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import *

def home(request):
    return render(request,'pages/index.html')
    
    
def termsCondition(request):
    return render(request,'pages/index.html')
    
def privacyPolicy(request):
    return render(request,'pages/index.html')
    
def subscription(request):
    if request.method=='POST':
   	 subscriptionemail = request.POST['subscriptionemail']
   	 
   	 subscription = Subscription(subscriptionemail=subscriptionemail)
   	 subscription.save()
    return redirect('home')

portfolio/views.py
from django.shortcuts import render
from .models import Posts

def testimonial(request):
    posts = Posts.objects.all()
    return render(request, 'pages/testimonials.html', {'posts': posts})

service/views.py
from django.shortcuts import render, HttpResponse

def service(request):
    return render(request,'pages/service.html')

testimonial/views.py
from django.shortcuts import render
from .models import Post

def testimonial(request):
    posts = Post.objects.all()
    return render(request, 'pages/testimonials.html', {'posts': posts})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Ganapati &mdash; Shopee </title>
  <meta name="description" content="NotSecure | IT Security Solution">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="IT, business, Repairing , Electronics , gadgets , mobile , drone , laptop , kitchen ">
	<meta name="author" content="Adrian">
  <link href="{% static 'assets/img/favicon.ico' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Muli:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>
<body>
  <section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:debojoty18@gmail.com">debojoty18@gmail.com</a></i>
        <i class="bi bi-phone d-flex align-items-center ms-4"><span>+91 62963 24431</span></i>
      </div>
       <div class="social-links d-none d-md-flex align-items-center">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
      </div>
    </div>
  </section>
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex justify-content-between">
      <div class="logo">
        <h1 class="text-light"><a href="/">Ganapati Shopee</a></h1>
      </div>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="/blog">Blog</a></li>
          <li><a href="{% url 'service' %}">Service</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'testimonial' %}">Testimonial</a></li>
          <li><a href="{% url 'contact' %}">Contact</a></li>         
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>
    </div>
  </header>
{% block body %} {% endblock %} 
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Ganapati Shopee</h3>
            <p>
              Debipur , Panpara <br>
              Purba Bardhaman , 713146<br>
              West Bengal <br><br>
              <strong>Phone:</strong> +91 62963 24431<br>
              <strong>Email:</strong> debojoty18@gmail.com<br>
            </p>
          </div>
          <div class="col-lg-2 col-md-6 footer-links">
	    <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>
          <div class="col-lg-3 col-md-6 footer-links">
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="/lab">Labs</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/training">Our Training</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/contact">Consultant</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/course">Our Courses</a><li>  
            </ul>
          </div>
          <div class="col-lg-4 col-md-6 footer-newsletter">
            <p>Join Our News Letter By Submitting your Email Id</p>
            <form action="/subscription" method="post">
            {% csrf_token %}
              <input type="email" id="subscriptionemail" name="subscriptionemail" placeholder="No Spam , We Promise"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="container d-md-flex py-4">
      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Adrianalvird</span></strong>. All Rights Reserved
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="WhatsApp"><i class="bx bxl-whatsapp"></i></a>
        <a href="#" class="Telegram"><i class="bx bxl-telegram"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        <a href="#" class="YouTube"><i class="bx bxl-youtube"></i></a>
        <a href="#" class="Snapchat"><i class="bx bxl-snapchat"></i></a>
      </div>
    </div>
  </footer>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center">
          <h2>About</h2>
          <ol>
            <li><a href="/">Home</a></li>
            <li>About</li>
          </ol>
        </div>
      </div>
    </section>
    <section id="about-us" class="about-us">
      <div class="container">
        <div class="row no-gutters">
          <div class="image col-xl-5 d-flex align-items-stretch justify-content-center justify-content-lg-start" data-aos="fade-right"></div>
          <div class="col-xl-7 ps-0 ps-lg-5 pe-lg-1 d-flex align-items-stretch">
            <div class="content d-flex flex-column justify-content-center">
              <h2 data-aos="fade-up"><b>Ganapati Shopee - Your Reliable Electric Device Repairing Service</b></h2>
              <p data-aos="fade-up">
               Welcome to Ganapati Shopee, your one-stop-shop for all your electric device repairing needs. With a team of expert technicians and a customer-centric approach, we are committed to delivering top-notch repairs for smartphones, laptops, household appliances, and more. Trust us to get your devices up and running efficiently and affordably. Contact us today for reliable and prompt service!
              </p>
              <div class="row">
                <div class="col-md-6 icon-box" data-aos="fade-up">
                  <i class="bx bx-receipt"></i>
                   <h4>Conditions</h4>
                  <p>Once we have successfully repaired your device, we will notify you immediately. You are required to collect the device from our store within 1 months from the date of repair completion.</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
                  <i class="bx bx-phone"></i>
                  <h4>Notification</h4>
                  <p> We will make reasonable efforts to inform you through the contact details provided during the repair intake process (phone number, email, etc.) once your device is ready for collection.</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
                  <i class="bx bx-shield"></i>
                  <h4>Security</h4>
                  <p>At Ganapati Shopee, we prioritize data security, ensuring your personal information remains safe and in the right format throughout the repair process.</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
                  <i class="bx bx-video"></i>
                  <h4>Repairing Info</h4>
                  <p>To maintain transparency, we provide a video of the repair before you make any payment, allowing you to verify the quality of our work.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section id="team" class="team section-bg">
      <div class="container">
        <div class="section-title" data-aos="fade-up">
          <h2>Our <strong>Team </strong> Members</h2>
          <p>At Ganapati Shopee, we take pride in our small yet highly skilled team of experts who are dedicated to providing top-quality electric device repairing services. Meet our team members:</p>
        </div>
        <div class="row">
          {% for member in members %}
<div class="col-lg-3 col-md-6 d-flex align-items-stretch">
  <div class="member" data-aos="fade-up">
    <div class="member-img">
      <img src="{{ member.image.url }}" class="img-fluid" alt="">
      <div class="social">
        {% if member.twitter_link %}
        <a href="{{ member.twitter_link }}"><i class="bi bi-twitter"></i></a>
        {% endif %}
        {% if member.facebook_link %}
        <a href="{{ member.facebook_link }}"><i class="bi bi-facebook"></i></a>
        {% endif %}
        {% if member.instagram_link %}
        <a href="{{ member.instagram_link }}"><i class="bi bi-instagram"></i></a>
        {% endif %}
        {% if member.linkedin_link %}
        <a href="{{ member.linkedin_link }}"><i class="bi bi-linkedin"></i></a>
        {% endif %}
        {% if member.website_link %}
        <a href="{{ member.facebook_link }}"><i class="bi bi-facebook"></i></a>
        {% endif %}
      </div>
    </div>
    <div class="member-info">
      <h4>{{ member.name }}</h4>
      <span>{{ member.role }}</span>
    </div>
  </div>
</div>
{% endfor %}
        </div>
      </div>
    </section>
  </main>
{% endblock %}

templates/pages/blog-details.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center">
          <h2>Repairing Details</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Portfolio Details</li>
          </ol>
        </div>
      </div>
    </section>
    <section id="portfolio-details" class="portfolio-details">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-8">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">
                <div class="swiper-slide">
                {% if post.video %}
		<video width="640" height="360" controls>
    		    <source src="{{post.video.url}}" type="video/mp4">
    		    Your browser does not support the video tag.
   		 </video>
   		 {% endif %}
		</div>
		{% if post.image1 %}
                <div class="swiper-slide">
                  <img src="{{post.image1.url}}" alt="">
                </div>
  		{% endif %}
  		{% if post.image2 %}
                <div class="swiper-slide">
                  <img src="{{post.image2.url}}" alt="">
                </div>
  		{% endif %}
  		{% if post.image3 %}
                <div class="swiper-slide">
                  <img src="{{post.image3.url}}" alt="">
                </div>
  		{% endif %}
  		{% if post.image4 %}
                <div class="swiper-slide">
                  <img src="{{post.image4.url}}" alt="">
                </div>
  		{% endif %}
  		{% if post.image5 %}
                <div class="swiper-slide">
                  <img src="{{post.image5.url}}" alt="">
                </div>
  		{% endif %}
              </div>
              <div class="swiper-pagination"></div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="portfolio-info">
              <h3>About Product</h3>
              <ul>
                <li><strong>Product Name</strong>: {{ post.name }}</li>
                <li><strong>Issue ID</strong>: {{ post.issueID }}</li>
                <li><strong>Category</strong>: {{ post.category }}</li>
                <li><strong>Client</strong>: {{ post.client }}</li>
                <li><strong>Project Issue</strong>: {{ post.project_issue }}</li>
                <li><strong>Project Finished</strong>: {{ post.project_finish }}</li>
                <li><strong>Repairing Cost</strong>: <i>₹{{ post.repairing_cost }}</i></li>
              </ul>
            </div>
            <div class="portfolio-description">
              <h2>About Issue </h2>
              <p>
                {{post.description}} 
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
<p><a href="{% url 'blog:blog_list' %}">&laquo; Back to all posts</a></p>
{% endblock %}

templates/pages/blog.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center">       
          <h2>Repairing Videos</h2>
          <ol>
            <li><a href="/">Home</a></li>
            <li>Blogs</li>
          </ol>
        </div>
      </div>
    </section>
    <section id="portfolio" class="portfolio">
      <div class="container">
        <div class="row" data-aos="fade-up">
          <div class="col-lg-12 d-flex justify-content-center">
            <ul id="portfolio-flters">
              <li data-filter="*" class="filter-active">All</li>
              <li data-filter=".filter-solar">Solar</li>
              <li data-filter=".filter-mobile">Mobile</li>
              <li data-filter=".filter-drone">Drone</li>
              <li data-filter=".filter-computer">Computer</li>
              <li data-filter=".filter-charger">Charger</li>
              <li data-filter=".filter-kitchen">Kitchens</li>
              <li data-filter=".filter-other">Other</li>
            </ul>
          </div>
        </div>
        <div class="row portfolio-container" data-aos="fade-up">
{% for post in page_obj %}
         <div class="col-lg-4 col-md-6 portfolio-item filter-{{post.category}}">
            <img src="{{post.thumbnail.url}}" class="img-fluid" alt="{{post.description}}">
            <div class="portfolio-info">
              <h4><a href="{% url 'blog:blog_detail' post.pk %}">{{ post.name }}</a></h4> 
            </div>
          </div>
{% endfor %}
        </div>
      </div>
<div class="blog-pagination">
  <ul class="justify-content-center">
    {% if page_obj.has_previous %}
      <li><a href="?page=1">&laquo; first</a></li>
      <li><a href="?page={{ page_obj.previous_page_number }}">previous</a></li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
      {% if num == page_obj.number %}
        <li class="active"><a href="#">{{ num }}</a></li>
      {% else %}
        <li><a href="?page={{ num }}">{{ num }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">next</a></li>
      <li><a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
    {% endif %}
  </ul>
</div>
  </main>
{% endblock %}

templates/pages/contact.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center">
          <h2>Contact</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Contact</li>
          </ol>
        </div>

      </div>
    </section>
    <section id="contact" class="contact">
      <div class="container">
        <div class="row justify-content-center" data-aos="fade-up">
          <div class="col-lg-10">
            <div class="info-wrap">
              <div class="row">
                <div class="col-lg-4 info">
                  <i class="bi bi-geo-alt"></i>
                  <h4>Location:</h4>
                  <p>Debipur [R.S.] , Purba Bardhaman<br>West Bengal , 713146</p>
                </div>
                <div class="col-lg-4 info mt-4 mt-lg-0">
                  <i class="bi bi-envelope"></i>
                  <h4>Email:</h4>
                  <p>debojoty18@gmail.com</p>
                </div>
                <div class="col-lg-4 info mt-4 mt-lg-0">
                  <i class="bi bi-phone"></i>
                  <h4>Call:</h4>
                  <p>+91 62963 24431</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row mt-5 justify-content-center" data-aos="fade-up">
          <div class="col-lg-10">
            <form action="{% url 'contact' %}" method="post" role="form" enctype="multipart/form-data" class="php-email-form">
            {% csrf_token %}
              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="text" name="fullname" class="form-control" id="fullname" placeholder="Your Name" required>
                </div>
                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                </div>
              </div>
              <div class="form-group mt-3">
                <input type="tel" class="form-control" name="phonenumber" id="phonenumber" placeholder="Phone Number" required>
              </div>
              <div class="form-group mt-3">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
              </div>
              <div class="form-group mt-3">
                <textarea class="form-control" name="description" rows="5" placeholder="description" required></textarea>
              </div>
              
              <div class="text-center"><button type="submit">Send Message</button></div>
            </form>
          </div>
        </div>
      </div>
    </section>
    <section id="cta-pricing" class="cta-pricing">
      <div class="container">
        <div class="text-center">
          <h3>Quick Consultancy Service</h3>
          <p> For any Technical issue if you can't get in touch with us , you can direct call us for inquiry service </p>
          <a class="cta-btn" href="#">Call Us</a>
        </div>
      </div>
    </section>
  </main>
{% endblock %}

templates/pages/testimonials.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center">
          <h2>Testimonials</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Testimonials</li>
          </ol>
        </div>
      </div>
    </section>
    <section id="testimonials" class="testimonials">
      <div class="container">
        <div class="row">
 {% for post in posts %}
          <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">
            <div class="testimonial-item mt-4 mt-lg-0">
              <img src="{{post.image.url}}" class="testimonial-img" alt="">
              <h3>{{post.name}}</h3>
              <h4><i>{{post.role}}</i></h4>
              <h4>{{post.link}}</h4>
              <p>
                <i class="bx bxs-quote-alt-left quote-icon-left"></i>
               {{post.comment}}
                <i class="bx bxs-quote-alt-right quote-icon-right"></i>
              </p>
            </div>
          </div>
         {% endfor %}
        </div>
      </div>
    </section>
  </main>
{% endblock %}